[package]

name = "zip"
version = "0.1.0"
authors = ["Mathijs van de Nes <git@mathijs.vd-nes.nl>"]
license = "MIT"
repository = "https://github.com/mvdnes/zip-rs.git"
description = """
Library to support the reading and writing of zip files.
"""

[dependencies]
flate2 = "*"
time = "*"

[dependencies.bzip2]
git = "https://github.com/mvdnes/bzip2-rs"
branch = "new_io"
