[package]

name = "zip"
version = "0.0.1"
authors = ["Mathijs van de Nes <git@mathijs.vd-nes.nl>"]

[dependencies.flate2]
git = "https://github.com/alexcrichton/flate2-rs.git"

[dependencies.time]
git = "http://github.com/rust-lang/time"

[[bin]]
name = "extract"
test = false
doc = false

[[bin]]
name = "write_sample"
test = false
doc = false
