[package]

name = "zip"
version = "0.0.1"
authors = ["Mathijs van de Nes <git@mathijs.vd-nes.nl>"]

[dependencies]
flate2 = "*"
time = "*"

[[bin]]
name = "extract"
test = false
doc = false

[[bin]]
name = "write_sample"
test = false
doc = false
