[package]

name = "zip"
version = "0.1.0"
authors = ["Mathijs van de Nes <git@mathijs.vd-nes.nl>"]
license = "MIT"
repository = "https://github.com/mvdnes/zip-rs.git"
description = """
Library to support the reading and writing of zip files.
"""

[dependencies]
flate2 = "^0.2"
bzip2 = "^0.2"
time = "*"
