[package]
name = "zip"
version = "0.5.13"
authors = ["Mathijs van de Nes <git@mathijs.vd-nes.nl>", "Marli Frost <marli@frost.red>", "Ryan Levick <ryan.levick@gmail.com>"]
license = "MIT"
repository = "https://github.com/zip-rs/zip.git"
keywords = ["zip", "archive"]
description = """
Library to support the reading and writing of zip files.
"""
edition = "2018"

[dependencies]
aes = "0.5.0"
byteorder = "1.3"
bzip2 = { version = "0.4", optional = true }
constant_time_eq = "0.1.5"
crc32fast = "1.0"
flate2 = { version = "1.0.0", default-features = false, optional = true }
hmac = "0.9.0"
pbkdf2 = "0.5.0"
sha-1 = "0.9.1"
thiserror = "1.0"
time = { version = "0.1", optional = true }

[dev-dependencies]
bencher = "0.1"
rand = "0.7"
walkdir = "2"

[features]
deflate = ["flate2/rust_backend"]
deflate-miniz = ["flate2/default"]
deflate-zlib = ["flate2/zlib"]
unreserved = []
default = ["bzip2", "deflate", "time"]

[[bench]]
name = "read_entry"
harness = false
